version: "3.8"

networks:
  nginx-reverse-proxy-test:
    driver: bridge

services:
  app-one:
    build:
      context: ./app-one/.
    # ports:
    #  - "2076:2076"
    networks:
      - nginx-reverse-proxy-test
    command: [nginx-debug, "-g", "daemon off;"]

  app-two:
    build:
      context: ./app-two/.
    # ports:
    #  - "2074:2074"
    networks:
      - nginx-reverse-proxy-test
    command: [nginx-debug, "-g", "daemon off;"]

  proxy:
    build:
      context: ./proxy/.
    links:
      - app-one
      - app-two
    ports:
      - "31116:31116"
      - "31114:31114"
    networks:
      - nginx-reverse-proxy-test
